-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 09:39:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ifspStoreBD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ifspStoreBD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ifspStoreBD` DEFAULT CHARACTER SET utf8 ;
USE `ifspStoreBD` ;

-- -----------------------------------------------------
-- Table `ifspStoreBD`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifspStoreBD`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Senha` VARCHAR(45) NULL,
  `Login` VARCHAR(45) NULL,
  `DataCadastro` TIMESTAMP NULL,
  `DataLogin` TIMESTAMP NULL,
  `Ativo` BINARY NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifspStoreBD`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifspStoreBD`.`Grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifspStoreBD`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifspStoreBD`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Preço` DECIMAL(10,2) NULL,
  `Quantidade` INT NULL,
  `DataCompra` DATE NULL,
  `UnidadeVenda` VARCHAR(10) NULL,
  `idGrupo` INT NOT NULL,
  PRIMARY KEY (`id`, `idGrupo`),
  INDEX `fk_Produto_Grupo_idx` (`idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Grupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `ifspStoreBD`.`Grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifspStoreBD`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifspStoreBD`.`Cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Estado` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifspStoreBD`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifspStoreBD`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NULL,
  `Endereco` VARCHAR(100) NULL,
  `Documento` VARCHAR(45) NULL,
  `Bairro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `idCidade` INT NOT NULL,
  PRIMARY KEY (`id`, `idCidade`),
  INDEX `fk_Cliente_Cidade1_idx` (`idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Cidade1`
    FOREIGN KEY (`idCidade`)
    REFERENCES `ifspStoreBD`.`Cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifspStoreBD`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifspStoreBD`.`Venda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Data` TIMESTAMP NULL,
  `ValorTotal` DECIMAL(10,2) NULL,
  `idCliente` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`id`, `idCliente`, `idUsuario`),
  INDEX `fk_Venda_Cliente1_idx` (`idCliente` ASC) VISIBLE,
  INDEX `fk_Venda_Usuario1_idx` (`idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `ifspStoreBD`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `ifspStoreBD`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ifspStoreBD`.`VendaItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ifspStoreBD`.`VendaItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Quantidade` INT NULL,
  `ValorUnitario` DECIMAL(10,2) NULL,
  `ValorTotal` DECIMAL(10,2) NULL,
  `idVenda` INT NOT NULL,
  `idProduto` INT NOT NULL,
  PRIMARY KEY (`id`, `idVenda`, `idProduto`),
  INDEX `fk_VendaItem_Venda1_idx` (`idVenda` ASC) VISIBLE,
  INDEX `fk_VendaItem_Produto1_idx` (`idProduto` ASC) VISIBLE,
  CONSTRAINT `fk_VendaItem_Venda1`
    FOREIGN KEY (`idVenda`)
    REFERENCES `ifspStoreBD`.`Venda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VendaItem_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `ifspStoreBD`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
